version: "3.9"

x-environment-variables: &environment-variables
  TELEGRAM_BOT_TOKEN: <bot-token>
  GOOGLE_SHEET_KEY: 1DL2pLSwZLe3BQtXMjjbXPbtIHiAxVU1HZH3mOETu49Q
  DATABASE_DSN: postgresql://docker:docker@postgres:5432/database

x-service-account-volumes: &service-account-volumes
  volumes:
    - /path/to/service_account.json:/code/data/service_account.json


services:
  refresher:
    build:
      dockerfile: Dockerfile-backend
    depends_on:
      - postgres
    command: python scripts/refresh.py
    <<: *service-account-volumes
    environment: *environment-variables
  notifier:
    build:
      dockerfile: Dockerfile-backend
    depends_on:
      - postgres
    command: python scripts/notify.py
    environment: *environment-variables
  polling:
    build:
      dockerfile: Dockerfile-backend
    depends_on:
      - postgres
    command: python scripts/polling.py
    environment: *environment-variables
  backend:
    build:
      dockerfile: Dockerfile-backend
    depends_on:
      - postgres
    command: flask run -h 0.0.0.0
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app/webapp/backend
      <<: *environment-variables
  frontend:
    build:
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    command: npm start
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_HOST: 127.0.0.1
      REACT_APP_BACKEND_PORT: 5000
  postgres:
    build:
      dockerfile: Dockerfile-postgres
