FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/code

WORKDIR /code
RUN mkdir data
COPY ./requirements.txt /code
RUN pip install -r requirements.txt
COPY . /code